# Generated by Django 4.2.23 on 2025-06-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_catch_fishingsession_delete_fishlog_catch_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='species',
            field=models.CharField(choices=[('pike', 'Pike'), ('perch', 'Perch'), ('trout', 'Trout'), ('zander', 'Zander'), ('salmon', 'Salmon'), ('roach', 'Roach'), ('tench', 'Tench'), ('other', 'Other')], max_length=50),
        ),
    ]
